version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: nour
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Streetsense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  my_python_app:
    build: ./my_python_app
    container_name: my_python_app
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=nour
      - DB_PASSWORD=123
      - DB_NAME=Streetsense
    volumes:
      - ./my_python_app:/app

volumes:
  postgres_data:

